plugins {
	id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

repositories {
	mavenCentral()
}

loom {
	splitEnvironmentSourceSets()

	mods {
		"pokeradar" {
			sourceSet sourceSets.main
			sourceSet sourceSets.client
		}
	}
}

dependencies {
	minecraft "com.mojang:minecraft:${project.minecraft_version}"
	mappings loom.officialMojangMappings()

	modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"
	modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

	// Cobblemon (local jar)
	modImplementation files("libs/Cobblemon-fabric-1.7.3+1.21.1.jar")

	modImplementation "org.jetbrains.kotlin:kotlin-stdlib:1.9.24"
	modImplementation "org.jetbrains.kotlin:kotlin-reflect:1.9.24"
}

processResources {
	inputs.property "version", project.version

	filesMatching("fabric.mod.json") {
		expand "version": inputs.properties.version
	}
}

tasks.withType(JavaCompile).configureEach {
	it.options.release = 21
}

java {
	sourceCompatibility = JavaVersion.VERSION_21
	targetCompatibility = JavaVersion.VERSION_21
}

jar {
	inputs.property "projectName", project.name

	from("LICENSE") {
		rename { "${it}_${project.name}" }
	}
}

tasks.named("remapJar") {
	archiveFileName.set("CobblemonRadar-1.0.0+1.21.1.jar")
}

tasks.register("copyToMods", Copy) {
	dependsOn remapJar

	from(tasks.named("remapJar"))
	into("C:\\Users\\Dominik\\AppData\\Roaming\\ModrinthApp\\profiles\\Pokeradar\\mods")

	duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

publishing {
	publications {
		create("mavenJava", MavenPublication) {
			from components.java
		}
	}

	repositories {
	}
}